sudo: required
services: 
  - docker

before_install: 
  - docker build -t ibukunawosika/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ibukunawosika/react-test npm test -- --coverage

after_success:
  - docker build -t ibukunawosika/multi-client ./client
  - docker build -t ibukunawosika/multi-service ./service
  - docker build -t ibukunawosika/multi-worker ./worker
  - docker build -t ibukunawosika/multi-nginx ./nginx

  #login to docker hub 
  - echo "supastar*93" | docker login -u | "ibukunawosika" --password-stdin

  #push images to dockerhub 
  - docker push ibukunawosika/multi-client
  - docker push ibukunawosika/multi-service
  - docker push ibukunawosika/multi-worker
  - docker push ibukunawosika/multi-nginx